#!/usr/bin/env python3
"""
Writes the scene headers for pathtracer.c.

Pick one at compile time with  -DSCENE_FILE='"scene_cornell.h"'.
scene.h is the default scene from build_scene(), which gpu/scenes.py
also uses for its hero scene.

Walls/floors are r=1000 spheres (like smallpt) so spheres stay the only
primitive.
"""

import numpy as np

R = 1000.0
LAMBERTIAN, METAL, DIELECTRIC, EMISSIVE = 0, 1, 2, 3
PREAMBLE = """#ifndef SCENE_H
#define SCENE_H

typedef enum { LAMBERTIAN=0, METAL=1, DIELECTRIC=2, EMISSIVE=3 } Mat;

typedef struct { float cx, cy, cz, r; float ar, ag, ab; int mat; float param; } Sphere;
"""


def build_scene():
    """Default scene as arrays: centers, radii, albedos, mats, params."""
    centers, radii, albedos, mats, params = [], [], [], [], []

    def add(center, radius, albedo, mat, param=0.0):
        centers.append(center)
        radii.append(radius)
        albedos.append(albedo)
        mats.append(mat)
        params.append(param)

    # ground, big enough to pass for a plane. pathtracer.c draws the checker
    add((0.0, -1000.0, 0.0), 1000.0, (0.0, 0.0, 0.0), LAMBERTIAN, 1.0)

    # main row
    add((0.0, 1.0, 0.0), 1.0, (1.0, 1.0, 1.0), DIELECTRIC, 1.52)   # glass
    add((-2.35, 1.0, -0.35), 1.0, (0.72, 0.28, 0.22), LAMBERTIAN)   # clay
    add((2.35, 1.0, -0.35), 1.0, (0.93, 0.87, 0.74), METAL, 0.04)   # gold

    # negative radius = inward normals, makes the glass ball hollow
    add((0.0, 1.0, 0.0), -0.82, (1.0, 1.0, 1.0), DIELECTRIC, 1.52)

    # warm key light (off screen) + cool rim light
    add((-6.0, 7.5, 4.0), 2.2, (10.0, 7.4, 4.6), EMISSIVE)
    add((7.5, 3.0, -6.0), 1.6, (1.6, 3.0, 5.2), EMISSIVE)

    # small random spheres, fixed seed so the scene is reproducible
    rng = np.random.default_rng(20260922)
    for _ in range(38):
        r = float(rng.uniform(0.14, 0.26))
        ang = float(rng.uniform(0, 2 * np.pi))
        dist = float(rng.uniform(2.0, 8.5))
        cx, cz = np.cos(ang) * dist, np.sin(ang) * dist - 1.0
        if abs(cx) < 3.6 and abs(cz) < 1.4:
            continue  # don't overlap the main row
        roll = rng.random()
        if roll < 0.55:
            tint = rng.uniform(0.15, 0.85, 3)
            add((cx, r, cz), r, tuple(tint * tint), LAMBERTIAN)
        elif roll < 0.85:
            tint = rng.uniform(0.55, 1.0, 3)
            add((cx, r, cz), r, tuple(tint), METAL, float(rng.uniform(0.0, 0.25)))
        else:
            add((cx, r, cz), r, (1.0, 1.0, 1.0), DIELECTRIC, 1.5)

    return (
        np.array(centers, np.float64),
        np.array(radii, np.float64),
        np.array(albedos, np.float64),
        np.array(mats, np.int32),
        np.array(params, np.float64),
    )


def f3(v):
    return ", ".join(f"{x:.6f}f" for x in v)


def emit(path, title, spheres, knobs):
    out = [f"/* {title}. Generated by make_scenes.py, don't edit. */", PREAMBLE]
    for key, val in knobs.items():
        out.append(f"#define {key:<14} {val}")
    out += ["", f"#define N_SPHERES {len(spheres)}", "",
            "static const Sphere SCENE[N_SPHERES] = {"]
    for (c, r, alb, mat, param) in spheres:
        out.append(f"  {{ {f3(c)}, {r:.6f}f, {f3(alb)}, {mat}, {param:.6f}f }},")
    out += ["};", "", "#endif", ""]
    with open(path, "w") as fh:
        fh.write("\n".join(out))
    lights = sum(1 for s in spheres if s[3] == "EMISSIVE")
    print(f"{path}: {len(spheres)} spheres, {lights} lights")


def hero():
    """scene.h, the default scene.

    Uses its own format (signed positions) so the output matches the
    committed scene.h exactly.
    """
    import os

    here = os.path.dirname(os.path.abspath(__file__))
    c, r, a, m, p = build_scene()

    names = {0: "LAMBERTIAN", 1: "METAL", 2: "DIELECTRIC", 3: "EMISSIVE"}
    out = ["/* Default scene. Generated by make_scenes.py, don't edit. */",
           "#ifndef SCENE_H", "#define SCENE_H", "",
           "typedef enum { LAMBERTIAN=0, METAL=1, DIELECTRIC=2, EMISSIVE=3 } Mat;", "",
           "typedef struct { float cx, cy, cz, r; float ar, ag, ab; int mat; float param; } Sphere;",
           "", f"#define N_SPHERES {len(r)}", "",
           "static const Sphere SCENE[N_SPHERES] = {"]
    for i in range(len(r)):
        out.append(
            "  {{ {:+.6f}f, {:+.6f}f, {:+.6f}f, {:+.6f}f, "
            "{:.6f}f, {:.6f}f, {:.6f}f, {}, {:.6f}f }},".format(
                c[i, 0], c[i, 1], c[i, 2], r[i],
                a[i, 0], a[i, 1], a[i, 2], names[int(m[i])], p[i]))
    out += ["};", "", "#endif"]
    with open(os.path.join(here, "scene.h"), "w") as fh:
        fh.write("\n".join(out) + "\n")
    lights = int((m == 3).sum())
    print(f"scene.h: {len(r)} spheres, {lights} lights")


def cornell():
    """Cornell box."""
    white = (0.73, 0.71, 0.68)
    red = (0.63, 0.065, 0.05)
    green = (0.14, 0.45, 0.091)
    s = [
        ((0, -R, 0), R, white, "LAMBERTIAN", 0),              # floor
        ((0, 2 + R, 0), R, white, "LAMBERTIAN", 0),           # ceiling
        ((0, 1, -1 - R), R, white, "LAMBERTIAN", 0),          # back wall
        ((-1 - R, 1, 0), R, red, "LAMBERTIAN", 0),            # left wall
        ((1 + R, 1, 0), R, green, "LAMBERTIAN", 0),           # right wall
        ((0, 1, 3.6 + R), R, (0, 0, 0), "LAMBERTIAN", 0),     # black wall behind camera
        ((-0.45, 0.42, -0.40), 0.42, (0.95, 0.95, 0.95), "METAL", 0.0),   # mirror ball
        ((0.47, 0.42, 0.22), 0.42, (1, 1, 1), "DIELECTRIC", 1.5),         # glass ball
        # lamp just under the ceiling, low enough that most shadow rays
        # aimed at it don't hit the ceiling first
        ((0, 1.95, 0), 0.20, (15, 12, 8), "EMISSIVE", 0),
    ]
    knobs = {
        "CAM_FROM": "0.0f, 1.0f, 3.4f",
        "CAM_AT": "0.0f, 1.0f, 0.0f",
        "CAM_VFOV": "38.0f",
        "CAM_APERTURE": "0.0f",
        "SKY_HORIZON": "0.0f, 0.0f, 0.0f",
        "SKY_ZENITH": "0.0f, 0.0f, 0.0f",
        "FLOOR_CHECKER": "0",
        "EXPOSURE": "1.0f",
    }
    emit("scene_cornell.h", "Cornell box", s, knobs)


def neon():
    """Night scene, lots of small coloured lights, big aperture for bokeh."""
    rng = np.random.default_rng(7)
    palette = [
        (6.0, 0.35, 2.4),    # magenta
        (0.25, 2.8, 6.0),    # cyan
        (6.0, 2.2, 0.15),    # amber
        (0.4, 6.0, 1.4),     # green
        (2.6, 0.5, 6.0),     # violet
    ]
    s = [
        ((0, -R, 0), R, (0.05, 0.05, 0.06), "LAMBERTIAN", 0),          # dark floor
        ((0, 1.0, 0), 1.0, (1, 1, 1), "DIELECTRIC", 1.5),              # glass ball
        ((0, 1.0, 0), -0.94, (1, 1, 1), "DIELECTRIC", 1.5),            # inner shell
        ((-2.3, 0.8, -1.2), 0.8, (0.92, 0.92, 0.96), "METAL", 0.0),    # chrome
        ((2.1, 0.7, -0.6), 0.7, (0.80, 0.80, 0.80), "LAMBERTIAN", 0),  # matte white
        # close lights for coloured rim lighting on the big spheres
        ((-1.25, 0.25, 1.1), 0.25, (7.0, 0.4, 2.8), "EMISSIVE", 0),
        ((1.35, 0.2, 1.35), 0.20, (0.3, 3.4, 7.0), "EMISSIVE", 0),
        ((0.9, 2.6, -1.8), 0.22, (7.0, 2.6, 0.2), "EMISSIVE", 0),
    ]

    def orb(x, y, z, r, boost=1.0):
        col = palette[int(rng.integers(len(palette)))]
        s.append(((x, y, z), r, tuple(c * boost for c in col), "EMISSIVE", 0))

    # background orbs, out of focus -> bokeh
    for _ in range(26):
        z = float(rng.uniform(-14, -4))
        half = (7.5 - z) * 0.44
        orb(float(rng.uniform(-half, half)), float(rng.uniform(0.15, 3.2)), z,
            float(rng.uniform(0.07, 0.16)), boost=1.6)
    # a few on the floor in the midground
    for _ in range(8):
        r = float(rng.uniform(0.07, 0.12))
        x = float(rng.choice([-1, 1]) * rng.uniform(1.0, 4.5))
        orb(x, r, float(rng.uniform(-3.5, 2.5)), r)
    # foreground, right in front of the lens -> big blurry discs
    for x, y, z in [(-1.0, 0.55, 5.3), (1.15, 1.45, 5.0), (0.45, 0.25, 5.6)]:
        orb(x, y, z, 0.06, boost=1.3)

    knobs = {
        "CAM_FROM": "0.0f, 1.1f, 7.5f",
        "CAM_AT": "0.0f, 0.9f, 0.0f",
        "CAM_VFOV": "28.0f",
        "CAM_APERTURE": "0.35f",
        "SKY_HORIZON": "0.012f, 0.010f, 0.025f",
        "SKY_ZENITH": "0.001f, 0.001f, 0.004f",
        "FLOOR_CHECKER": "0",
        "EXPOSURE": "1.0f",
    }
    emit("scene_neon.h", "Neon night", s, knobs)


if __name__ == "__main__":
    hero()
    cornell()
    neon()
