#!/usr/bin/env python3
"""
Generate scene headers for pathtracer.c.

Each header defines the sphere list plus any camera/sky/exposure overrides,
and is compiled in with:  cc ... -DSCENE_FILE='"scene_cornell.h"' ...

Walls and floors are spheres of radius 1000 -- the smallpt trick. At this
scale their curvature is under a millimetre across the room, and it keeps
the renderer to a single primitive.
"""

import numpy as np

R = 1000.0
PREAMBLE = """#ifndef SCENE_H
#define SCENE_H

typedef enum { LAMBERTIAN=0, METAL=1, DIELECTRIC=2, EMISSIVE=3 } Mat;

typedef struct { float cx, cy, cz, r; float ar, ag, ab; int mat; float param; } Sphere;
"""


def f3(v):
    return ", ".join(f"{x:.6f}f" for x in v)


def emit(path, title, spheres, knobs):
    out = [f"/* {title} -- generated by make_scenes.py, do not edit by hand. */", PREAMBLE]
    for key, val in knobs.items():
        out.append(f"#define {key:<14} {val}")
    out += ["", f"#define N_SPHERES {len(spheres)}", "",
            "static const Sphere SCENE[N_SPHERES] = {"]
    for (c, r, alb, mat, param) in spheres:
        out.append(f"  {{ {f3(c)}, {r:.6f}f, {f3(alb)}, {mat}, {param:.6f}f }},")
    out += ["};", "", "#endif", ""]
    with open(path, "w") as fh:
        fh.write("\n".join(out))
    lights = sum(1 for s in spheres if s[3] == "EMISSIVE")
    print(f"{path}: {len(spheres)} spheres, {lights} lights")


def cornell():
    """The Cornell box: the standard test of colour bleeding and soft shadows."""
    white = (0.73, 0.71, 0.68)
    red = (0.63, 0.065, 0.05)
    green = (0.14, 0.45, 0.091)
    s = [
        ((0, -R, 0), R, white, "LAMBERTIAN", 0),              # floor
        ((0, 2 + R, 0), R, white, "LAMBERTIAN", 0),           # ceiling
        ((0, 1, -1 - R), R, white, "LAMBERTIAN", 0),          # back wall
        ((-1 - R, 1, 0), R, red, "LAMBERTIAN", 0),            # left wall
        ((1 + R, 1, 0), R, green, "LAMBERTIAN", 0),           # right wall
        ((0, 1, 3.6 + R), R, (0, 0, 0), "LAMBERTIAN", 0),     # black wall behind camera
        ((-0.45, 0.42, -0.40), 0.42, (0.95, 0.95, 0.95), "METAL", 0.0),   # mirror ball
        ((0.47, 0.42, 0.22), 0.42, (1, 1, 1), "DIELECTRIC", 1.5),         # glass ball
        # Globe lamp hugging the ceiling. Mostly below it, so shadow rays
        # aimed at it rarely land on ceiling instead.
        ((0, 1.95, 0), 0.20, (15, 12, 8), "EMISSIVE", 0),
    ]
    knobs = {
        "CAM_FROM": "0.0f, 1.0f, 3.4f",
        "CAM_AT": "0.0f, 1.0f, 0.0f",
        "CAM_VFOV": "38.0f",
        "CAM_APERTURE": "0.0f",
        "SKY_HORIZON": "0.0f, 0.0f, 0.0f",
        "SKY_ZENITH": "0.0f, 0.0f, 0.0f",
        "FLOOR_CHECKER": "0",
        "EXPOSURE": "1.0f",
    }
    emit("scene_cornell.h", "Cornell box", s, knobs)


def neon():
    """Night scene: dozens of small coloured lights and a wide-open lens."""
    rng = np.random.default_rng(7)
    palette = [
        (6.0, 0.35, 2.4),    # magenta
        (0.25, 2.8, 6.0),    # cyan
        (6.0, 2.2, 0.15),    # amber
        (0.4, 6.0, 1.4),     # green
        (2.6, 0.5, 6.0),     # violet
    ]
    s = [
        ((0, -R, 0), R, (0.05, 0.05, 0.06), "LAMBERTIAN", 0),          # dark floor
        ((0, 1.0, 0), 1.0, (1, 1, 1), "DIELECTRIC", 1.5),              # glass hero
        ((0, 1.0, 0), -0.94, (1, 1, 1), "DIELECTRIC", 1.5),            # hollow it out
        ((-2.3, 0.8, -1.2), 0.8, (0.92, 0.92, 0.96), "METAL", 0.0),    # chrome
        ((2.1, 0.7, -0.6), 0.7, (0.80, 0.80, 0.80), "LAMBERTIAN", 0),  # matte catcher
        # Key lights close to the heroes for strong coloured rims.
        ((-1.25, 0.25, 1.1), 0.25, (7.0, 0.4, 2.8), "EMISSIVE", 0),
        ((1.35, 0.2, 1.35), 0.20, (0.3, 3.4, 7.0), "EMISSIVE", 0),
        ((0.9, 2.6, -1.8), 0.22, (7.0, 2.6, 0.2), "EMISSIVE", 0),
    ]

    def orb(x, y, z, r, boost=1.0):
        col = palette[int(rng.integers(len(palette)))]
        s.append(((x, y, z), r, tuple(c * boost for c in col), "EMISSIVE", 0))

    # Far field: out of focus, these become the bokeh discs.
    for _ in range(26):
        z = float(rng.uniform(-14, -4))
        half = (7.5 - z) * 0.44
        orb(float(rng.uniform(-half, half)), float(rng.uniform(0.15, 3.2)), z,
            float(rng.uniform(0.07, 0.16)), boost=1.6)
    # A few resting on the floor mid-ground, lighting pools around them.
    for _ in range(8):
        r = float(rng.uniform(0.07, 0.12))
        x = float(rng.choice([-1, 1]) * rng.uniform(1.0, 4.5))
        orb(x, r, float(rng.uniform(-3.5, 2.5)), r)
    # Foreground, very close to the lens: huge soft discs.
    for x, y, z in [(-1.0, 0.55, 5.3), (1.15, 1.45, 5.0), (0.45, 0.25, 5.6)]:
        orb(x, y, z, 0.06, boost=1.3)

    knobs = {
        "CAM_FROM": "0.0f, 1.1f, 7.5f",
        "CAM_AT": "0.0f, 0.9f, 0.0f",
        "CAM_VFOV": "28.0f",
        "CAM_APERTURE": "0.35f",
        "SKY_HORIZON": "0.012f, 0.010f, 0.025f",
        "SKY_ZENITH": "0.001f, 0.001f, 0.004f",
        "FLOOR_CHECKER": "0",
        "EXPOSURE": "1.0f",
    }
    emit("scene_neon.h", "Neon night", s, knobs)


if __name__ == "__main__":
    cornell()
    neon()
