#!/usr/bin/env python3
"""
Writes the scene headers for pathtracer.c.

Pick one at compile time with  -DSCENE_FILE='"scene_cornell.h"'.
scene.h is the default scene from build_scene(), which gpu/scenes.py
also uses for its hero scene.

Objects:
  sphere  ((x, y, z), radius, (r, g, b), "MAT", param)
  plane   ((nx, ny, nz), offset, (r, g, b), "MAT", param)   all p with n.p = offset
  box     ((x, y, z), (sx, sy, sz), (r, g, b), "MAT", param[, rot_y])
          centre, full size, optional rotation around y in degrees

MAT is LAMBERTIAN, METAL (param = fuzz), DIELECTRIC (param = ior) or
EMISSIVE. The older scenes use r=1000 spheres as walls, from before
planes existed.
"""

import numpy as np

R = 1000.0
LAMBERTIAN, METAL, DIELECTRIC, EMISSIVE = 0, 1, 2, 3
MATS = ("LAMBERTIAN", "METAL", "DIELECTRIC", "EMISSIVE")
PREAMBLE = """#ifndef SCENE_H
#define SCENE_H
"""


def build_scene():
    """Default scene as arrays: centers, radii, albedos, mats, params."""
    centers, radii, albedos, mats, params = [], [], [], [], []

    def add(center, radius, albedo, mat, param=0.0):
        centers.append(center)
        radii.append(radius)
        albedos.append(albedo)
        mats.append(mat)
        params.append(param)

    # ground, big enough to pass for a plane. pathtracer.c draws the checker
    add((0.0, -1000.0, 0.0), 1000.0, (0.0, 0.0, 0.0), LAMBERTIAN, 1.0)

    # main row
    add((0.0, 1.0, 0.0), 1.0, (1.0, 1.0, 1.0), DIELECTRIC, 1.52)   # glass
    add((-2.35, 1.0, -0.35), 1.0, (0.72, 0.28, 0.22), LAMBERTIAN)   # clay
    add((2.35, 1.0, -0.35), 1.0, (0.93, 0.87, 0.74), METAL, 0.04)   # gold

    # negative radius = inward normals, makes the glass ball hollow
    add((0.0, 1.0, 0.0), -0.82, (1.0, 1.0, 1.0), DIELECTRIC, 1.52)

    # warm key light (off screen) + cool rim light
    add((-6.0, 7.5, 4.0), 2.2, (10.0, 7.4, 4.6), EMISSIVE)
    add((7.5, 3.0, -6.0), 1.6, (1.6, 3.0, 5.2), EMISSIVE)

    # small random spheres, fixed seed so the scene is reproducible
    rng = np.random.default_rng(20260922)
    for _ in range(38):
        r = float(rng.uniform(0.14, 0.26))
        ang = float(rng.uniform(0, 2 * np.pi))
        dist = float(rng.uniform(2.0, 8.5))
        cx, cz = np.cos(ang) * dist, np.sin(ang) * dist - 1.0
        if abs(cx) < 3.6 and abs(cz) < 1.4:
            continue  # don't overlap the main row
        roll = rng.random()
        if roll < 0.55:
            tint = rng.uniform(0.15, 0.85, 3)
            add((cx, r, cz), r, tuple(tint * tint), LAMBERTIAN)
        elif roll < 0.85:
            tint = rng.uniform(0.55, 1.0, 3)
            add((cx, r, cz), r, tuple(tint), METAL, float(rng.uniform(0.0, 0.25)))
        else:
            add((cx, r, cz), r, (1.0, 1.0, 1.0), DIELECTRIC, 1.5)

    return (
        np.array(centers, np.float64),
        np.array(radii, np.float64),
        np.array(albedos, np.float64),
        np.array(mats, np.int32),
        np.array(params, np.float64),
    )


def f3(v):
    return ", ".join(f"{x:.6f}f" for x in v)


def emit(path, title, spheres, knobs, planes=(), boxes=()):
    for obj in (*spheres, *planes, *boxes):
        if obj[3] not in MATS:
            raise ValueError(f"{path}: unknown material {obj[3]!r}, use one of {MATS}")
    for sph in spheres:
        if sph[1] == 0:
            raise ValueError(f"{path}: sphere at {sph[0]} has radius 0")
    for pl in planes:
        if not any(pl[0]):
            raise ValueError(f"{path}: plane normal can't be (0, 0, 0)")
    for b in boxes:
        if min(b[1]) <= 0:
            raise ValueError(f"{path}: box at {b[0]} needs a positive size, got {b[1]}")

    out = [f"/* {title}. Generated by make_scenes.py, don't edit. */", PREAMBLE]
    for key, val in knobs.items():
        out.append(f"#define {key:<14} {val}")
    out += ["", f"#define N_SPHERES {len(spheres)}"]
    if spheres:
        out += ["static const Sphere SCENE[N_SPHERES] = {"]
        for (c, r, alb, mat, param) in spheres:
            out.append(f"  {{ {f3(c)}, {r:.6f}f, {f3(alb)}, {mat}, {param:.6f}f }},")
        out += ["};"]
    if planes:
        out += ["", f"#define N_PLANES {len(planes)}",
                "static const Plane PLANES[N_PLANES] = {"]
        for (n, off, alb, mat, param) in planes:
            out.append(f"  {{ {f3(n)}, {off:.6f}f, {f3(alb)}, {mat}, {param:.6f}f }},")
        out += ["};"]
    if boxes:
        out += ["", f"#define N_BOXES {len(boxes)}",
                "static const Box BOXES[N_BOXES] = {"]
        for b in boxes:
            c, size, alb, mat, param = b[:5]
            rot = b[5] if len(b) > 5 else 0.0
            out.append(f"  {{ {f3(c)}, {f3(size)}, {rot:.6f}f, {f3(alb)}, {mat}, {param:.6f}f }},")
        out += ["};"]
    out += ["", "#endif", ""]
    with open(path, "w") as fh:
        fh.write("\n".join(out))
    lights = sum(1 for o in (*spheres, *planes, *boxes) if o[3] == "EMISSIVE")
    print(f"{path}: {len(spheres)} spheres, {len(planes)} planes, "
          f"{len(boxes)} boxes, {lights} lights")


def hero():
    """scene.h, the default scene.

    Uses its own format (signed positions) so the output matches the
    committed scene.h exactly.
    """
    import os

    here = os.path.dirname(os.path.abspath(__file__))
    c, r, a, m, p = build_scene()

    names = {0: "LAMBERTIAN", 1: "METAL", 2: "DIELECTRIC", 3: "EMISSIVE"}
    out = ["/* Default scene. Generated by make_scenes.py, don't edit. */",
           "#ifndef SCENE_H", "#define SCENE_H",
           "", f"#define N_SPHERES {len(r)}", "",
           "static const Sphere SCENE[N_SPHERES] = {"]
    for i in range(len(r)):
        out.append(
            "  {{ {:+.6f}f, {:+.6f}f, {:+.6f}f, {:+.6f}f, "
            "{:.6f}f, {:.6f}f, {:.6f}f, {}, {:.6f}f }},".format(
                c[i, 0], c[i, 1], c[i, 2], r[i],
                a[i, 0], a[i, 1], a[i, 2], names[int(m[i])], p[i]))
    out += ["};", "", "#endif"]
    with open(os.path.join(here, "scene.h"), "w") as fh:
        fh.write("\n".join(out) + "\n")
    lights = int((m == 3).sum())
    print(f"scene.h: {len(r)} spheres, {lights} lights")


def cornell():
    """Cornell box."""
    white = (0.73, 0.71, 0.68)
    red = (0.63, 0.065, 0.05)
    green = (0.14, 0.45, 0.091)
    s = [
        ((0, -R, 0), R, white, "LAMBERTIAN", 0),              # floor
        ((0, 2 + R, 0), R, white, "LAMBERTIAN", 0),           # ceiling
        ((0, 1, -1 - R), R, white, "LAMBERTIAN", 0),          # back wall
        ((-1 - R, 1, 0), R, red, "LAMBERTIAN", 0),            # left wall
        ((1 + R, 1, 0), R, green, "LAMBERTIAN", 0),           # right wall
        ((0, 1, 3.6 + R), R, (0, 0, 0), "LAMBERTIAN", 0),     # black wall behind camera
        ((-0.45, 0.42, -0.40), 0.42, (0.95, 0.95, 0.95), "METAL", 0.0),   # mirror ball
        ((0.47, 0.42, 0.22), 0.42, (1, 1, 1), "DIELECTRIC", 1.5),         # glass ball
        # lamp just under the ceiling, low enough that most shadow rays
        # aimed at it don't hit the ceiling first
        ((0, 1.95, 0), 0.20, (15, 12, 8), "EMISSIVE", 0),
    ]
    knobs = {
        "CAM_FROM": "0.0f, 1.0f, 3.4f",
        "CAM_AT": "0.0f, 1.0f, 0.0f",
        "CAM_VFOV": "38.0f",
        "CAM_APERTURE": "0.0f",
        "SKY_HORIZON": "0.0f, 0.0f, 0.0f",
        "SKY_ZENITH": "0.0f, 0.0f, 0.0f",
        "FLOOR_CHECKER": "0",
        "EXPOSURE": "1.0f",
    }
    emit("scene_cornell.h", "Cornell box", s, knobs)


def cornell_boxes():
    """Classic Cornell box: plane walls, two rotated boxes."""
    white = (0.73, 0.71, 0.68)
    red = (0.63, 0.065, 0.05)
    green = (0.14, 0.45, 0.091)
    planes = [
        ((0, 1, 0), 0.0, white, "LAMBERTIAN", 0),     # floor, y = 0
        ((0, -1, 0), -2.0, white, "LAMBERTIAN", 0),   # ceiling, y = 2
        ((0, 0, 1), -1.0, white, "LAMBERTIAN", 0),    # back, z = -1
        ((1, 0, 0), -1.0, red, "LAMBERTIAN", 0),      # left, x = -1
        ((-1, 0, 0), -1.0, green, "LAMBERTIAN", 0),   # right, x = 1
        ((0, 0, -1), -3.6, (0, 0, 0), "LAMBERTIAN", 0),  # behind the camera
    ]
    boxes = [
        ((-0.33, 0.6, -0.35), (0.58, 1.2, 0.58), white, "LAMBERTIAN", 0, 18.0),   # tall
        ((0.34, 0.3, 0.3), (0.58, 0.6, 0.58), white, "LAMBERTIAN", 0, -17.0),     # short
    ]
    spheres = [((0, 1.95, 0), 0.20, (15, 12, 8), "EMISSIVE", 0)]
    knobs = {
        "CAM_FROM": "0.0f, 1.0f, 3.4f",
        "CAM_AT": "0.0f, 1.0f, 0.0f",
        "CAM_VFOV": "38.0f",
        "CAM_APERTURE": "0.0f",
        "SKY_HORIZON": "0.0f, 0.0f, 0.0f",
        "SKY_ZENITH": "0.0f, 0.0f, 0.0f",
        "FLOOR_CHECKER": "0",
        "EXPOSURE": "1.0f",
    }
    emit("scene_boxes.h", "Cornell box with boxes", spheres, knobs, planes, boxes)


def neon():
    """Night scene, lots of small coloured lights, big aperture for bokeh."""
    rng = np.random.default_rng(7)
    palette = [
        (6.0, 0.35, 2.4),    # magenta
        (0.25, 2.8, 6.0),    # cyan
        (6.0, 2.2, 0.15),    # amber
        (0.4, 6.0, 1.4),     # green
        (2.6, 0.5, 6.0),     # violet
    ]
    s = [
        ((0, -R, 0), R, (0.05, 0.05, 0.06), "LAMBERTIAN", 0),          # dark floor
        ((0, 1.0, 0), 1.0, (1, 1, 1), "DIELECTRIC", 1.5),              # glass ball
        ((0, 1.0, 0), -0.94, (1, 1, 1), "DIELECTRIC", 1.5),            # inner shell
        ((-2.3, 0.8, -1.2), 0.8, (0.92, 0.92, 0.96), "METAL", 0.0),    # chrome
        ((2.1, 0.7, -0.6), 0.7, (0.80, 0.80, 0.80), "LAMBERTIAN", 0),  # matte white
        # close lights for coloured rim lighting on the big spheres
        ((-1.25, 0.25, 1.1), 0.25, (7.0, 0.4, 2.8), "EMISSIVE", 0),
        ((1.35, 0.2, 1.35), 0.20, (0.3, 3.4, 7.0), "EMISSIVE", 0),
        ((0.9, 2.6, -1.8), 0.22, (7.0, 2.6, 0.2), "EMISSIVE", 0),
    ]

    def orb(x, y, z, r, boost=1.0):
        col = palette[int(rng.integers(len(palette)))]
        s.append(((x, y, z), r, tuple(c * boost for c in col), "EMISSIVE", 0))

    # background orbs, out of focus -> bokeh
    for _ in range(26):
        z = float(rng.uniform(-14, -4))
        half = (7.5 - z) * 0.44
        orb(float(rng.uniform(-half, half)), float(rng.uniform(0.15, 3.2)), z,
            float(rng.uniform(0.07, 0.16)), boost=1.6)
    # a few on the floor in the midground
    for _ in range(8):
        r = float(rng.uniform(0.07, 0.12))
        x = float(rng.choice([-1, 1]) * rng.uniform(1.0, 4.5))
        orb(x, r, float(rng.uniform(-3.5, 2.5)), r)
    # foreground, right in front of the lens -> big blurry discs
    for x, y, z in [(-1.0, 0.55, 5.3), (1.15, 1.45, 5.0), (0.45, 0.25, 5.6)]:
        orb(x, y, z, 0.06, boost=1.3)

    knobs = {
        "CAM_FROM": "0.0f, 1.1f, 7.5f",
        "CAM_AT": "0.0f, 0.9f, 0.0f",
        "CAM_VFOV": "28.0f",
        "CAM_APERTURE": "0.35f",
        "SKY_HORIZON": "0.012f, 0.010f, 0.025f",
        "SKY_ZENITH": "0.001f, 0.001f, 0.004f",
        "FLOOR_CHECKER": "0",
        "EXPOSURE": "1.0f",
    }
    emit("scene_neon.h", "Neon night", s, knobs)


def mirrors():
    """Two facing mirrors: the balls between them repeat into the distance."""
    planes = [((0, 1, 0), 0.0, (0.8, 0.8, 0.8), "LAMBERTIAN", 0)]   # checker floor
    # Mirrors are thin boxes, not planes: two infinite planes would close
    # off the sky (every ray that isn't exactly parallel hits one), and
    # with no lamp the scene would be black. The slight green tint is what
    # real mirrors do, and it makes each reflection a little darker.
    glass = (0.80, 0.88, 0.84)
    boxes = [
        ((-2.0, 1.3, -1.0), (0.04, 2.6, 12.0), glass, "METAL", 0.0),
        ((2.0, 1.3, -1.0), (0.04, 2.6, 12.0), glass, "METAL", 0.0),
    ]
    spheres = [
        ((-0.9, 0.35, 1.0), 0.35, (1, 1, 1), "DIELECTRIC", 1.5),
        ((0.3, 0.45, 0.2), 0.45, (0.75, 0.12, 0.1), "LAMBERTIAN", 0),
        ((-0.5, 0.3, -0.8), 0.3, (1.0, 0.78, 0.34), "METAL", 0.02),
        ((0.9, 0.25, -1.6), 0.25, (0.1, 0.3, 0.75), "LAMBERTIAN", 0),
    ]
    # lit by the sky only: a small lamp seen through the mirrors turns into
    # thousands of fireflies on the floor, since NEE can't see it that way
    knobs = {
        "CAM_FROM": "1.5f, 1.4f, 4.8f",
        "CAM_AT": "-1.0f, 0.5f, -0.6f",
        "CAM_VFOV": "42.0f",
        "CAM_APERTURE": "0.0f",
        "SKY_HORIZON": "0.70f, 0.72f, 0.76f",
        "SKY_ZENITH": "0.25f, 0.36f, 0.60f",
        "FLOOR_CHECKER": "1",
        "EXPOSURE": "1.0f",
    }
    emit("scene_mirrors.h", "Infinity mirrors", spheres, knobs, planes, boxes)


def domino_path(n=16):
    """Centres and rot_y (degrees) along an S-curve, evenly spaced along it."""
    t = np.linspace(0.0, 1.0, 2001)
    x = -2.4 + 4.8 * t
    z = 0.9 * np.sin(t * 2 * np.pi)
    arc = np.concatenate([[0.0], np.cumsum(np.hypot(np.diff(x), np.diff(z)))])
    out = []
    for d in np.linspace(0.0, arc[-1], n):
        i = min(int(np.searchsorted(arc, d)), len(t) - 2)
        dx, dz = x[i + 1] - x[i], z[i + 1] - z[i]
        # a box's local z axis points along (sin a, cos a) in x/z for rot_y = a,
        # so this turns the thin side of each domino along the path
        out.append(((float(x[i]), float(z[i])), float(np.degrees(np.arctan2(dx, dz)))))
    return out


def dominoes():
    """A line of dominoes along an S-curve, low warm light."""
    planes = [((0, 1, 0), 0.0, (0.42, 0.27, 0.16), "LAMBERTIAN", 0)]   # wooden floor
    boxes = [((x, 0.25, z), (0.25, 0.5, 0.07), (0.86, 0.85, 0.8), "LAMBERTIAN", 0, a)
             for (x, z), a in domino_path()]
    spheres = [
        ((-2.9, 0.22, 0.15), 0.22, (0.75, 0.1, 0.08), "METAL", 0.1),     # the ball that starts it
        ((4.5, 1.1, 3.0), 0.35, (110, 75, 40), "EMISSIVE", 0),          # low warm lamp
    ]
    knobs = {
        "CAM_FROM": "0.8f, 2.6f, 5.2f",
        "CAM_AT": "0.0f, 0.2f, 0.0f",
        "CAM_VFOV": "38.0f",
        "CAM_APERTURE": "0.06f",
        "SKY_HORIZON": "0.10f, 0.09f, 0.10f",
        "SKY_ZENITH": "0.03f, 0.04f, 0.07f",
        "FLOOR_CHECKER": "0",
        "EXPOSURE": "1.0f",
    }
    emit("scene_dominoes.h", "Dominoes", spheres, knobs, planes, boxes)


BALL_COLOURS = [(0.85, 0.65, 0.05), (0.05, 0.15, 0.6), (0.7, 0.05, 0.05), (0.3, 0.05, 0.4),
                (0.85, 0.3, 0.02), (0.05, 0.35, 0.1), (0.4, 0.07, 0.05), (0.02, 0.02, 0.02)]


def billiard_rack(r=0.1, apex_z=-0.4):
    """15 ball centres in a triangle, apex toward the camera (+z)."""
    balls, k = [], 0
    for row in range(5):
        z = apex_z - row * r * np.sqrt(3.0) * 1.001
        for j in range(row + 1):
            x = (j - row / 2) * 2 * r * 1.001
            balls.append(((float(x), r, float(z)), BALL_COLOURS[k % len(BALL_COLOURS)]))
            k += 1
    return balls


def billiards():
    """Racked balls on a felt table under two lamps."""
    planes = [((0, 1, 0), -0.9, (0.12, 0.08, 0.06), "LAMBERTIAN", 0)]  # room floor, y = -0.9
    wood = (0.35, 0.16, 0.07)
    boxes = [
        ((0, -0.05, 0), (4.0, 0.1, 2.2), (0.06, 0.32, 0.12), "LAMBERTIAN", 0),    # felt top, y = 0
        ((0, -0.5, 0), (3.6, 0.8, 1.8), (0.1, 0.06, 0.04), "LAMBERTIAN", 0),      # table body
        ((0, 0.04, -1.16), (4.3, 0.18, 0.12), wood, "LAMBERTIAN", 0),             # rails
        ((0, 0.04, 1.16), (4.3, 0.18, 0.12), wood, "LAMBERTIAN", 0),
        ((-2.06, 0.04, 0), (0.12, 0.18, 2.2), wood, "LAMBERTIAN", 0),
        ((2.06, 0.04, 0), (0.12, 0.18, 2.2), wood, "LAMBERTIAN", 0),
    ]
    spheres = [(c, 0.1, col, "LAMBERTIAN", 0) for c, col in billiard_rack()]
    spheres += [
        ((0.35, 0.1, 1.0), 0.1, (0.9, 0.88, 0.82), "LAMBERTIAN", 0),     # cue ball
        ((-0.9, 1.9, 0), 0.22, (22, 19, 14), "EMISSIVE", 0),             # lamps
        ((0.9, 1.9, 0), 0.22, (22, 19, 14), "EMISSIVE", 0),
    ]
    knobs = {
        "CAM_FROM": "1.1f, 0.75f, 2.7f",
        "CAM_AT": "0.0f, 0.08f, -0.5f",
        "CAM_VFOV": "32.0f",
        "CAM_APERTURE": "0.02f",
        "SKY_HORIZON": "0.0f, 0.0f, 0.0f",
        "SKY_ZENITH": "0.0f, 0.0f, 0.0f",
        "FLOOR_CHECKER": "0",
        "EXPOSURE": "1.0f",
    }
    emit("scene_billiards.h", "Billiards", spheres, knobs, planes, boxes)


def gallery():
    """Three pedestals: glass, gold and a mirror cube."""
    planes = [
        ((0, 1, 0), 0.0, (0.8, 0.8, 0.8), "LAMBERTIAN", 0),           # checker floor
        ((0, 0, 1), -2.5, (0.78, 0.76, 0.72), "LAMBERTIAN", 0),       # back wall, z = -2.5
    ]
    white = (0.8, 0.79, 0.76)
    boxes = [((x, 0.5, -1.0), (0.6, 1.0, 0.6), white, "LAMBERTIAN", 0) for x in (-1.6, 0.0, 1.6)]
    boxes.append(((1.6, 1.25, -1.0), (0.5, 0.5, 0.5), (0.95, 0.95, 0.97), "METAL", 0.0, 40.0))
    spheres = [
        ((-1.6, 1.3, -1.0), 0.3, (1, 1, 1), "DIELECTRIC", 1.5),
        ((0.0, 1.3, -1.0), 0.3, (1.0, 0.78, 0.34), "METAL", 0.08),
    ]
    # big and dim rather than small and bright: same light, far fewer fireflies
    # from the lamps' reflections in the gold and the mirror cube
    spheres += [((x, 3.2, 0.4), 0.45, (5.0, 4.6, 3.8), "EMISSIVE", 0) for x in (-1.6, 0.0, 1.6)]
    knobs = {
        "CAM_FROM": "0.0f, 1.6f, 5.0f",
        "CAM_AT": "0.0f, 1.0f, -1.0f",
        "CAM_VFOV": "36.0f",
        "CAM_APERTURE": "0.0f",
        "SKY_HORIZON": "0.05f, 0.05f, 0.06f",
        "SKY_ZENITH": "0.02f, 0.02f, 0.03f",
        "FLOOR_CHECKER": "1",
        "EXPOSURE": "1.0f",
    }
    emit("scene_gallery.h", "Gallery", spheres, knobs, planes, boxes)


def stairs_steps(n=14):
    """Spiral steps: (centre, rot_y) with each step pointing out from the column."""
    out = []
    for i in range(n):
        a = np.radians(28.0 * i)
        # rot_y = a turns the box's local x axis to (cos a, -sin a) in x/z
        centre = (float(0.75 * np.cos(a)), 0.15 + 0.2 * i, float(-0.75 * np.sin(a)))
        out.append((centre, float(np.degrees(a))))
    return out


def stairs():
    """Spiral staircase around a column, sunset sky."""
    planes = [((0, 1, 0), 0.0, (0.8, 0.8, 0.8), "LAMBERTIAN", 0)]      # checker floor
    stone = (0.75, 0.72, 0.66)
    boxes = [((0, 1.6, 0), (0.35, 3.2, 0.35), stone, "LAMBERTIAN", 0)]  # column
    boxes += [(c, (1.1, 0.07, 0.38), stone, "LAMBERTIAN", 0, a) for c, a in stairs_steps()]
    top_c, top_a = stairs_steps()[-1]
    spheres = [
        ((top_c[0] * 1.25, top_c[1] + 0.035 + 0.14, top_c[2] * 1.25), 0.14, (1, 1, 1), "DIELECTRIC", 1.5),
        ((1.4, 0.2, 0.9), 0.2, (0.7, 0.12, 0.08), "LAMBERTIAN", 0),
        ((6.0, 6.0, 4.0), 0.8, (30, 22, 14), "EMISSIVE", 0),               # evening sun
    ]
    knobs = {
        "CAM_FROM": "3.6f, 2.0f, 4.6f",
        "CAM_AT": "0.0f, 1.3f, 0.0f",
        "CAM_VFOV": "42.0f",
        "CAM_APERTURE": "0.0f",
        "SKY_HORIZON": "0.55f, 0.35f, 0.25f",
        "SKY_ZENITH": "0.12f, 0.16f, 0.30f",
        "FLOOR_CHECKER": "1",
        "EXPOSURE": "0.9f",
    }
    emit("scene_stairs.h", "Spiral stairs", spheres, knobs, planes, boxes)


if __name__ == "__main__":
    hero()
    cornell()
    cornell_boxes()
    neon()
    mirrors()
    dominoes()
    billiards()
    gallery()
    stairs()
