/* Infinity mirrors. Generated by make_scenes.py, don't edit. */
#ifndef SCENE_H
#define SCENE_H

#define CAM_FROM       1.5f, 1.4f, 4.8f
#define CAM_AT         -1.0f, 0.5f, -0.6f
#define CAM_VFOV       42.0f
#define CAM_APERTURE   0.0f
#define SKY_HORIZON    0.70f, 0.72f, 0.76f
#define SKY_ZENITH     0.25f, 0.36f, 0.60f
#define FLOOR_CHECKER  1
#define EXPOSURE       1.0f

#define N_SPHERES 4
static const Sphere SCENE[N_SPHERES] = {
  { -0.900000f, 0.350000f, 1.000000f, 0.350000f, 1.000000f, 1.000000f, 1.000000f, DIELECTRIC, 1.500000f },
  { 0.300000f, 0.450000f, 0.200000f, 0.450000f, 0.750000f, 0.120000f, 0.100000f, LAMBERTIAN, 0.000000f },
  { -0.500000f, 0.300000f, -0.800000f, 0.300000f, 1.000000f, 0.780000f, 0.340000f, METAL, 0.020000f },
  { 0.900000f, 0.250000f, -1.600000f, 0.250000f, 0.100000f, 0.300000f, 0.750000f, LAMBERTIAN, 0.000000f },
};

#define N_PLANES 1
static const Plane PLANES[N_PLANES] = {
  { 0.000000f, 1.000000f, 0.000000f, 0.000000f, 0.800000f, 0.800000f, 0.800000f, LAMBERTIAN, 0.000000f },
};

#define N_BOXES 2
static const Box BOXES[N_BOXES] = {
  { -2.000000f, 1.300000f, -1.000000f, 0.040000f, 2.600000f, 12.000000f, 0.000000f, 0.800000f, 0.880000f, 0.840000f, METAL, 0.000000f },
  { 2.000000f, 1.300000f, -1.000000f, 0.040000f, 2.600000f, 12.000000f, 0.000000f, 0.800000f, 0.880000f, 0.840000f, METAL, 0.000000f },
};

#endif
