/* Suzanne. Generated by make_scenes.py, don't edit. */
#ifndef SCENE_H
#define SCENE_H

#define CAM_FROM       0.0f, 1.4f, 5.6f
#define CAM_AT         0.0f, 0.5f, 0.0f
#define CAM_VFOV       32.0f
#define CAM_APERTURE   0.03f
#define SKY_HORIZON    0.30f, 0.32f, 0.38f
#define SKY_ZENITH     0.06f, 0.08f, 0.14f
#define FLOOR_CHECKER  1
#define EXPOSURE       1.0f

#define N_SPHERES 2
static const Sphere SCENE[N_SPHERES] = {
  { -3.000000f, 4.500000f, 3.500000f, 0.900000f, 14.000000f, 12.000000f, 10.000000f, EMISSIVE, 0.000000f },
  { 5.000000f, 3.500000f, 0.500000f, 0.500000f, 10.000000f, 12.000000f, 17.000000f, EMISSIVE, 0.000000f },
};

#define N_PLANES 1
static const Plane PLANES[N_PLANES] = {
  { 0.000000f, 1.000000f, 0.000000f, 0.000000f, 0.800000f, 0.800000f, 0.800000f, LAMBERTIAN, 0.000000f },
};

#define MESH_FILE "scene_suzanne.mesh"   /* 47232 triangles */
#define N_MESH_MATS 3
static const MeshMat MESH_MATS[N_MESH_MATS] = {
  { 1.000000f, 1.000000f, 1.000000f, DIELECTRIC, 1.500000f },
  { 1.000000f, 0.780000f, 0.340000f, METAL, 0.050000f },
  { 0.700000f, 0.180000f, 0.120000f, LAMBERTIAN, 0.000000f },
};

#endif
